### ISSUE TITLE
del() cannot accept strings, but put() can

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#50]
```js
var jld = {"@context": "https://schema.org/", "name": "BigBlueHat"};
db.jsonld.put(jld, console.log.bind(console));
db.jsonld.put(JSON.stringify(jld), console.log.bind(console));
// have the same result
db.jsonld.del(jld, console.log.bind(console)); // works
db.jsonld.del(JSON.stringify(jld), console.log.bind(console)); // doesn't...
//results in...
```

**JsonLdError**
```js
{
  code: "loading document failed",
  url: "{"@context":{"@vocab":"http://xmlns.com/foaf/0.1/"},"@id":"http://bigbluehat.com/#","name":"BigBlueHat","knows":[{"@id":"http://manu.sporny.org#person","name":"Manu Sporny","homepage":"http://manu.sporny.org/"}]}",
  __proto__: {
    message: "URL could not be dereferenced; only "http" and "https" URLs are supported.",
    name: "jsonld.InvalidUrl",
    stack: "Error↵    at JsonLdError (http://localhost:8000/dist/index.js:20808:19)↵    at loader (http://localhost:8000/dist/index.js:20344:23)↵    at http://localhost:8000/dist/index.js:19809:8↵    at Function.jsonld.promisify (http://localhost:8000/dist/index.js:19808:10)↵    at jsonld.RequestQueue._loader (http://localhost:8000/dist/index.js:20337:21)↵    at http://localhost:8000/dist/index.js:19966:43↵    at jsonld.RequestQueue.add (http://localhost:8000/dist/index.js:19962:12)↵    at Object.jsonld.loadDocument [as documentLoader] (http://localhost:8000/dist/index.js:19670:24)↵    at http://localhost:8000/dist/index.js:18732:29↵    at Item.run (http://localhost:8000/dist/index.js:52966:14)"
  }
}
```

Apparently jsonld.js thinks any string is a URL, so input will need `JSON.parse()`'ing first.

**Comment by jmatsushita** [comment]
Good catch! Fix coming.

**Comment by jmatsushita** [comment]
Actually I can't reproduce the error. Neither with your `jld` var and the different one in the `url` key of the error. (Trying this in the console of the [playground](https://bigbluehat.github.io/levelgraph-playground/))

**Comment by jmatsushita** [comment]
Ah, just reproduced it finally.
